# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: mikf.gallery-dl.Nightly
PackageVersion: 2025.11.01
InstallerType: portable
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2025-11-01
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/gdl-org/builds/releases/download/2025.11.01/gallery-dl_windows_x86.exe
  InstallerSha256: 42A04B8F814626F6826528B27975527AD8CBD1B02DBEBB60DDD667BF2F420154
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  InstallerUrl: https://github.com/gdl-org/builds/releases/download/2025.11.01/gallery-dl_windows.exe
  InstallerSha256: F9C191892DB1FCDD8F02AE0F6DF0C516C9497FD019C1C2D318C9368B04888D86
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ManifestType: installer
ManifestVersion: 1.10.0
