# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JMMG.TextFileEditor
PackageVersion: '2.0'
InstallerType: exe
ReleaseDate: 2026-10-04
Installers:
- Architecture: x86
  InstallerUrl: https://www.jmmgc.com/downloads/Text_File_Editor_Standalone.exe
  InstallerSha256: 0D59C36EA6DA43D03C4B564F00233B9B721C4E9595D9150BEC16B87016082F5C 
- Architecture: x64
  InstallerUrl: https://www.jmmgc.com/downloads/Text_File_Editor_Standalone.exe
  InstallerSha256: 0D59C36EA6DA43D03C4B564F00233B9B721C4E9595D9150BEC16B87016082F5C
- Architecture: arm64
  InstallerUrl: https://www.jmmgc.com/downloads/Text_File_Editor_Standalone_ARM64.exe
  InstallerSha256: 8952355260B60A45BE76541467C4FD88973584C82A623EDCF5C638EA58B7792A
ManifestType: installer
ManifestVersion: 1.12.0
